# Generated by Django 4.0 on 2022-09-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_profreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profreview',
            old_name='ext',
            new_name='text',
        ),
    ]
