# Generated by Django 4.0 on 2022-09-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_ext_profreview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='prof',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='ProfReview',
        ),
    ]
