# Generated by Django 4.0 on 2022-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_review_prof_delete_profreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
