# Generated by Django 4.0 on 2022-09-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_review_prof_profreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
