# Generated by Django 4.0 on 2022-09-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_profreview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profreview',
            name='watchAgain',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
