# Generated by Django 4.1.1 on 2022-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_reviewer_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profreview",
            name="text",
            field=models.CharField(max_length=5000),
        ),
    ]
