# Generated by Django 4.1.1 on 2022-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_alter_profreview_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profreview",
            name="text",
            field=models.TextField(),
        ),
    ]
