# Generated by Django 4.1.1 on 2022-09-21 01:55

from django.db import migrations
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0014_alter_profreview_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profreview",
            name="text",
            field=movie.models.NonStrippingTextField(),
        ),
    ]
